### ISSUE TITLE
Weird Qwidget in 0.21 version causing issues in some theme's 

### ISSUE THREAD

**Issue by MisterMakerNL** [mdkus/PieMenu#9]
I posted the issue here:
https://github.com/FreeCAD/FreeCAD/issues/8440
Thought I post it here too, maybe you can fix it here which would probably be quicker than in main.

**Comment by mdkus** [comment]
Hi,
couldn't reproduce this in version 0.21.0.30492 (Git). I will try it with the actual version 0.21.0.31917...ok, I could reproduce the bug with the weird Qwidget. I'll do some tests...

**Comment by MisterMakerNL** [comment]
This issue got pretty blown up as it caused the menu to stop working even without piemenu. So it's already fixed as far as I understood.

**Comment by mdkus** [comment]
@MisterMakerNL  
I analyzed the code of my predecessor 'triplus' and found out, that it is a timing problem. The problem comes up when PieMenu is too fast when adding the 'AccessoriesMenu'. So triplus implemented a timer for waiting on FC to have loaded the default workbench with its initial menu bar. Addons which are real workbenches can fortunatly use workbenches method 'appendMenu', which avoids the problem somehow. So I reimplemented this timer in PieMenu version 1.2.7 and it should work even without the patch. Please confirm.

**Comment by MisterMakerNL** [comment]
Kinda hard testing something that isn;t broken :) but at least it didn't break it again!
